### PR TITLE
Improved repo setup

### PR DESCRIPTION
**Pull request by lipkau**
### Description
Improved Repository setup by:
* adding structure to .gitignore
* adding sublime project file

### Motivation and Context
* .gitignore is messy (still needs improving)
* when using Sublime, the dev can benefit from the project file

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ewerybody** [comment]
The project setup for sublime? Why isn't that covered with the `.editorconfig`? I actually wouldn't want to add code editor specific stuff to the project.

For .gitignore: I actually just cleaned it up a bit :D But:
Actually before adding stuff there we should decide if we actually need it in the project on github. If it's just personal stuff then it might just be ignored another way. See https://www.peterbe.com/plog/gitinfoexclude
The project setup for sublime? Why isn't that covered with the `.editorconfig`? I actually wouldn't want to add code editor specific stuff to the project.

For .gitignore: I actually just cleaned it up a bit, did you get the latest version? :D But:
Before adding stuff there we should decide if we actually need it in the project on github. If it's just personal stuff then it might just be ignored another way. See https://www.peterbe.com/plog/gitinfoexclude

Maybe we should rather ignore all `.something`? And actively include certain ones?

**Comment by lipkau** [comment]
copy paste error?

I like the link. And agree with that.
But we really need to clean up the .gitignore and the repo. it is really messy.

I will make a suggestion for the repo .gitignore and a wiki post on the local gitignore

**Comment by ewerybody** [comment]
Yep there was a copy paste error \*shrug\* 😆 
Is the .gitignore better this way?
About the repo: Well there is only one idiot "maintaining" this. I think it was already far messier before. Still room for improvement. True ✔️

**Comment by lipkau** [comment]
Question:
why are you ignoring /modules?
wouldn't it be useful to already have a submodule of a2.modules in there?

**Comment by ewerybody** [comment]
Yea that will be the case for a release but not for the development here.

I actually pointed the a2.modules project directly into /modules so i can handle that separately in the other project while both work together. Also I can tinker around there with half baked module sources ...

**Comment by ewerybody** [comment]
Ok. I'm closing this. .gitignore is less messier and editor specific things need to be solved another way. 🎉

**Pull request closed without merging**
